language: clojure
# Yeah, these need to go into separate repos :-/
install: (cd web; lein2 deps) && (cd swing; lein2 deps)
script: (cd web; lein2 cibuild) && (cd swing; lein2 cibuild)
lein: lein2
jdk:
  - oraclejdk7
  - openjdk7
